// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Msgype.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Logic.Pbf {

  /// <summary>Holder for reflection information generated from Msgype.proto</summary>
  public static partial class MsgypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Msgype.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxNc2d5cGUucHJvdG8SCUxvZ2ljLnBiZirhAgoHTXNnVHlwZRILCgdDU0xv",
            "Z2luEAASCwoHU0NMb2dpbhABEgwKCENTTG9nb3V0EAISDAoIU0NMb2dvdXQQ",
            "AxIPCgtDU0hlYXJ0QmVhdBAEEg8KC1NDSGVhcnRCZWF0EAUSDwoLQ1NSZWNv",
            "bm5lY3QQBhIPCgtTQ1JlY29ubmVjdBAHEhEKDUNTVGltZUNvcnJlY3QQCBIR",
            "Cg1TQ1RpbWVDb3JyZWN0EAkSDQoJU0NUaW1lTnRmEAoSDQoJU0NLaWNrT2Zm",
            "EAsSEAoLQ3NBZGRFbnRpdHkQzAgSEAoLU2NBZGRFbnRpdHkQzQgSEwoOQ3NS",
            "ZW1vdmVFbnRpdHkQzggSEwoOU2NSZW1vdmVFbnRpdHkQzwgSEwoOQ3NVcGRh",
            "dGVFbnRpdHkQ0AgSEwoOU2NVcGRhdGVFbnRpdHkQ0QgSDwoKQ3NPcEVudGl0",
            "eRDSCBIPCgpTY09wRW50aXR5ENMIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Logic.Pbf.MsgType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 框架层协议号，更换游戏项目依然可以使用
  /// 最大支持65535
  /// </summary>
  public enum MsgType {
    /// <summary>
    /// ----------------------- 框架层协议 ----------------------------
    /// </summary>
    [pbr::OriginalName("CSLogin")] Cslogin = 0,
    [pbr::OriginalName("SCLogin")] Sclogin = 1,
    [pbr::OriginalName("CSLogout")] Cslogout = 2,
    [pbr::OriginalName("SCLogout")] Sclogout = 3,
    [pbr::OriginalName("CSHeartBeat")] CsheartBeat = 4,
    [pbr::OriginalName("SCHeartBeat")] ScheartBeat = 5,
    [pbr::OriginalName("CSReconnect")] Csreconnect = 6,
    [pbr::OriginalName("SCReconnect")] Screconnect = 7,
    [pbr::OriginalName("CSTimeCorrect")] CstimeCorrect = 8,
    [pbr::OriginalName("SCTimeCorrect")] SctimeCorrect = 9,
    [pbr::OriginalName("SCTimeNtf")] SctimeNtf = 10,
    [pbr::OriginalName("SCKickOff")] SckickOff = 11,
    /// <summary>
    /// ----------------------- 逻辑层协议 ----------------------------
    /// sync
    /// </summary>
    [pbr::OriginalName("CsAddEntity")] CsAddEntity = 1100,
    [pbr::OriginalName("ScAddEntity")] ScAddEntity = 1101,
    [pbr::OriginalName("CsRemoveEntity")] CsRemoveEntity = 1102,
    [pbr::OriginalName("ScRemoveEntity")] ScRemoveEntity = 1103,
    [pbr::OriginalName("CsUpdateEntity")] CsUpdateEntity = 1104,
    [pbr::OriginalName("ScUpdateEntity")] ScUpdateEntity = 1105,
    [pbr::OriginalName("CsOpEntity")] CsOpEntity = 1106,
    [pbr::OriginalName("ScOpEntity")] ScOpEntity = 1107,
  }

  #endregion

}

#endregion Designer generated code
