using System;
using System.Collections.Generic;
using Ludiq.Peek;
using Ludiq.PeekCore;

[assembly: MapToPlugin(typeof(Changelog_1_3_2), PeekPlugin.ID)]

namespace Ludiq.Peek
{
	// ReSharper disable once RedundantUsingDirective
	using PeekCore;

	internal class Changelog_1_3_2 : PluginChangelog
	{
		public Changelog_1_3_2(Plugin plugin) : base(plugin) { }

		public override SemanticVersion version => "1.3.2";

		public override DateTime date => new DateTime(2020, 12, 05);

		public override IEnumerable<string> changes
		{
			get
			{
				yield return "[Added] Creator option to place created object as Child of picked object";
				yield return "[Optimized] Scene view integration by skipping MouseMove and Layout events";
				yield return "[Fixed] Issue where ToolControl.isPressed was not released after a DragExit event";
				yield return "[Fixed] Compatibility with ProBuilder 4.4.0 or newer";
				yield return "[Fixed] Flickering in scene toolbars when multiple scene views are shown in Unity 2020 URP";
				yield return "[Fixed] Group and Replace moving the targets to the active scene";
				yield return "[Fixed] Renamed AOT support DLL generated by Odin to avoid conflicts with other Odin Serializer instances in user projects";
			}
		}
	}
}